version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - microservices-network

  back:
    image: back:latest
    ports:
      - "5000:8080"
    networks:
      - microservices-network

  timeservice:
    image: timeservice:latest
    ports:
      - "5001:8080"
    networks:
      - microservices-network

  dataservice:
    image: dataservice:latest
    ports:
      - "5002:8080"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: overlay