version: '3.8'

services:
  timeservice:
    build:
      context: ./TimeService
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    networks:
      - microservices-network

  dataservice:
    build:
      context: ./DataService
      dockerfile: Dockerfile
    ports:
      - "5002:8080"
    networks:
      - microservices-network

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - timeservice
      - dataservice
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge