version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - back
      - timeservice
      - dataservice
    networks:
      - microservices-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  timeservice:
    build:
      context: ./TimeService
      dockerfile: Dockerfile
    networks:
      - microservices-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  dataservice:
    build:
      context: ./DataService
      dockerfile: Dockerfile
    networks:
      - microservices-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    depends_on:
      - timeservice
      - dataservice
    networks:
      - microservices-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  microservices-network:
    driver: overlay